version: 1.0.{build}

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
          Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

environment:
  TWINE_USERNAME: ardiloot
  TWINE_PASSWORD:
    secure: LpIfAMfey8cEO3mNGXR4h9cUXBNNVCRAWBpCVmn2vq8=
  matrix:
  - PYTHON_VERSION: 3.6.5
    MINICONDA: C:\Miniconda36-x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - PYTHON_VERSION: 3.5.5
    MINICONDA: C:\Miniconda36-x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    
install:
  - ps: $env:PATH += "$env:MINICONDA;$env:MINICONDA/Scripts"
  - ps: conda config --set always_yes yes --set changeps1 no
  - ps: conda update -q conda
  - ps: conda info -a
  - ps: conda create -q -n test-environment python=$env:PYTHON_VERSION numpy scipy Cython
  - cmd: activate test-environment
  - sh: source activate test-environment
  - ps: pip install -r requirements.txt
  - ps: pip install twine
  - ps: pip install pytest
  - ps: pip install pyyaml  

build_script:
  - ps: python setup.py build
  - ps: python setup.py install

test_script:
  - ps: pytest Tests/
  - ps: python setup.py sdist
  - cmd: python setup.py bdist_wheel
  - sh: python setup.py bdist_wheel

artifacts:
  - path: dist/*

deploy_script:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true"){
        twine upload --skip-existing dist/*
      } else {
        echo "Not deplaying because not a tagged commit."
      }