version: 1.0.{build}

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
          Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

environment:
  TWINE_USERNAME: ardiloot
  TWINE_PASSWORD:
    secure: LpIfAMfey8cEO3mNGXR4h9cUXBNNVCRAWBpCVmn2vq8=
  matrix:
  - PYTHON_VERSION: 3.6.3
    MINICONDA: C:\Miniconda36-x64
#  - PYTHON_VERSION: 3.5.2
#    MINICONDA: C:\Miniconda35-x64

install:
  - ps: $env:PATH += "$env:MINICONDA;$env:MINICONDA/Scripts"
  - ps: conda config --set always_yes yes --set changeps1 no
  - ps: conda update -q conda
  - ps: conda info -a
  - ps: conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy Cython
  - ps: activate test-environment
  - ps: pip install -r requirements.txt
  - ps: pip install twine
  - ps: pip install nose  

build_script:
  - ps: python setup.py build install

test_script:
  - ps: pytest Tests/
  - ps: python setup.py sdist bdist_wheel

artifacts:
  - path: dist/*

deploy_script:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true"){
        twine upload --skip-existing dist/*
      } else {
        echo "Not deplaying because not a tagged commit."
      }